site_name: Introduction to AL
repo_url: https://github.com/EDGZTNSR/IntroductionToAL
theme: readthedocs
nav:
  - Getting Started: index.md
  - Development in AL:
      - JSON: docs/json.md
      - Debugging: docs/debugging.md
      - Upgrade Extension: docs/ExtensionUpgrade.md
      - Common Error: docs/commonErrors.md
